name: Deploy to Environments

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'
      env:
        type: choice
        description: Environment to deploy to
        options:
          - dev
          - test
          - prod
        default: 'dev'

env:
  project-directory: ./
  repository: 'dadiorchen/treetracker-admin-client-test'


jobs:
  frontend:
    name: Build Frontend Project
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')
    steps:
      - name: Use Node.js 16.14.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.x'
      - name: Resolve channel, s3 bucket and distribution id secret name
        run: echo ::set-output name=CHANEL::$(echo `node -e ' process.env.GITHUB_REF_NAME === "master" ? console.log("master") :console.log(require("./.releaserc.json").branches.reduce((a,c) => a || c.name === process.env.GITHUB_REF_NAME  && c.channel, false))'`)
        id: resolver
      - name: Print resolved vars
        run: echo ${{ steps.resolver.outputs.CHANNEL }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}
      - name: Use Node.js 16.14.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.x'
      - name: npm clean install
        run: npm ci --legacy-peer-deps
        working-directory: ${{ env.project-directory }}
      # define the endpoints for PROD in github secrets
      - name: build frontend project
        run: npm run build:staging
        working-directory: ${{ env.project-directory }}
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-bundle
          path: build
  #      - name: run React tests
  #        run: npm test
  #        working-directory: ${{ env.project-directory }}

  deploy:
    name: Deploy to CDN
    runs-on: ubuntu-latest
    needs: frontend
    if: |
      github.repository == ${{ github.env.repository }}
    steps:
      - name: Resolve channel, s3 bucket and distribution id secret name
        run: echo ::set-output name=CHANEL::$(echo `node -e ' process.env.GITHUB_REF_NAME === "master" ? console.log("master") :console.log(require("./.releaserc.json").branches.reduce((a,c) => a || c.name === process.env.GITHUB_REF_NAME  && c.channel, false))'`)
        id: resolver
      - name: Print resolved vars
        run: echo ${{ steps.resolver.outputs.CHANNEL }}
      - name: Download bundled frontend resources
        uses: actions/download-artifact@v2
        with:
          name: frontend-bundle
          path: build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET }}
          aws-region: us-east-1
      - name: Copy front end resources to s3 bucket
        run: |
          aws s3 sync build s3://${{ secrets.STAGING_CDN_S3_BUCKET }} --delete
      - name: Invalidate cloudfront caches
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_CDN_DISTRIBUTION_ID }} --paths "/*"
