# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Admin Panel Client CI/CD Pipeline Next

on:
  push:
    branches:
      - freetown

env:
  project-directory: ./

jobs:
  client:
    name: Build Client Project
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')
    steps:
      # print github vars
      - name: Print github vars
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.actor: ${{ github.actor }}"
          echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
          echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
          echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
          echo "github.event.pull_request.base.sha: ${{ github.event.pull_request.base.sha }}"
          echo "github.event.pull_request.number: ${{ github.event.pull_request.number }}"
          echo "github.event.pull_request.title: ${{ github.event.pull_request.title }}"
          echo "github.event.pull_request.body: ${{ github.event.pull_request.body }}"
          echo "github.event.pull_request.user.login: ${{ github.event.pull_request.user.login }}"
          echo "github.event.pull_request.merged: ${{ github.event.pull_request.merged }}"
          echo "github.event.pull_request.mergeable: ${{ github.event.pull_request.mergeable }}"
          echo "github.event.pull_request.mergeable_state: ${{ github.event.pull_request.mergeable_state }}"
          echo "github.event.pull_request.merged_by.login: ${{ github.event.pull_request.merged_by.login }}"
          echo "github.event.pull_request.comments: ${{ github.event.pull_request.comments }}"
          echo "github.event.pull_request.review_comments: ${{ github.event.pull_request.review_comments }}"
          echo "github.event.pull_request.maintainer_can_modify: ${{ github.event.pull_request.maintainer_can_modify }}"
          echo "github.event.pull_request.commits: ${{ github.event.pull_request.commits }}"
          echo "github.event.pull_request.additions: ${{ github.event.pull_request.additions }}"
          echo "github.event.pull_request.deletions: ${{ github.event.pull_request.deletions }}"
          echo "github.event.pull_request.changed_files: ${{ github.event.pull_request.changed_files }}"
      - uses: actions/checkout@v2
      - name: Use Node.js 16.14.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.x'
      - name: npm clean install
        run: npm ci --legacy-peer-deps
        working-directory: ${{ env.project-directory }}
      - name: run ESLint
        run: npm run lint
        working-directory: ${{ env.project-directory }}
      - name: build client dev project
        if: github.event_name == 'push' && github.repository == 'Greenstand/treetracker-admin-client'
        run: npm run build:dev
        working-directory: ${{ env.project-directory }}
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && github.repository == 'Greenstand/treetracker-admin-client'
        with:
          name: client-bundle
          path: build-dev
      - name: build client project
        run: npm run build
        working-directory:
          ${{ env.project-directory }}
          #TODO      - name: run React tests
          #TODO        run: npm test
          #TODO        working-directory: ${{ env.project-directory }}
  release:
    name: Release semantic version
    needs: client
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') &&
      github.event_name == 'push' &&
      github.repository == 'Greenstand/treetracker-admin-client'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.x'
      # install dependencies and run semantic-release
      - run: npm i -g semantic-release @semantic-release/{git,exec,changelog}
      - run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  deploy:
    name: Deploy to dev CDN
    runs-on: ubuntu-latest
    needs: release
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') &&
      github.event_name == 'push' &&
      github.repository == 'Greenstand/treetracker-admin-client'
    steps:
      - uses: actions/checkout@v2
      - name: Download bundled client resources
        uses: actions/download-artifact@v2
        with:
          name: client-bundle
          path: build-dev
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - name: Copy front end resources to s3 bucket
        run: |
          aws s3 sync build-dev s3://${{ secrets.DEV_CDN_S3_BUCKET_FREETOWN }} --delete
      - name: Invalidate cloudfront caches
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_CDN_DISTRIBUTION_ID_FREETOWN }} --paths "/*"
